# Generated by Django 4.1.2 on 2022-10-22 09:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_service_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
