# Generated by Django 4.1.2 on 2022-10-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('progress', models.IntegerField(blank=True, default=80, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
